### ISSUE TITLE
Task RHEL-08-010380 does not check users other than ec2-user if executed against ec2

### ISSUE THREAD

**Issue by wdower** [MindPointGroup/RHEL8-STIG#17]
**Issue**

Task RHEL-08-010380 does not check users other than ec2-user if executed against ec2.

I ran this playbook against an ec2 with the following line in /etc/sudoers:
```
%wheel ALL=(ALL) NOPASSWD: ALL
```
The playbook didn't overwrite the NOPASSWD.

Checking the task code:
```yaml
- name: "MEDIUM | RHEL-08-010380 | PATCH | RHEL 8 must require users to provide a password for privilege escalation."
  replace:
      path: "{{ item }}"
      regexp: '^([^#|{% if system_is_ec2 %}ec2-user{% endif %}].*)NOPASSWD(.*)'
      replace: '\1PASSWD\2'
```
Looks like the regexp just ignores anything other than ec2-user for this task if executed against an ec2.

**Expected Behavior**
Running the playbook against an ec2 should catch _all_ users with NOPASSWD set, not just `ec2-user`.

**Actual Behavior**
Users who are not `ec2-user` are not matched by the regex when on an ec2.

**Control(s) Affected**
RHEL-08-010380

**Environment (please complete the following information):**
 - Ansible Version: 2.9.9
 - Ansible Server Python Version: 2.7.5

**Possible Solution**
Remove the ec2-user clause from the regex.

Opening this as an issue in case there's some reason for checking for an ec2-user that I can't think of.
